name: Fetch Social Content

on:
  schedule:
<<<<<<< HEAD
    - cron: "0 4 * * *" # once per day
=======
    - cron: "0 3 * * *" # once per day (UTC)
>>>>>>> eccd2b8 (reel added)
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
<<<<<<< HEAD

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

=======
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
>>>>>>> eccd2b8 (reel added)
      - run: node scripts/fetch-content.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
